name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::1.0
    - name: Build the Docker image
      run: docker build . --file docker-git-hello-world/Dockerfile --tag shady84/test:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push shady84/test:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build . --file docker-git-hello-world/Dockerfile --tag shady84/test:latest
    - name: Push the latest Docker image
      run: docker push shady84/test:latest
